name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # git_remote_url: 'ssh://dokku@146.190.111.95:22/excelpp'
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}